name: Plan IPFS Metadata Infrastructure

on:
  push:
    branches:
      - main

jobs:
  planIpfsInfrastructure:
    name: Plan IPFS Infrastructure
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Envs
        run: |
          mkdir ~/.aws
          echo -e "${{ secrets.SHARED_CREDENTIALS }}" >> ~/.aws/credentials
          echo -e "${{ secrets.SHARED_CONFIG }}" >> ~/.aws/config

      - name: Dev - Terraform Init
        working-directory: terraform/environments/dev
        run: terraform init

      - name: Dev - Terraform Plan
        working-directory: terraform/environments/dev
        run: terraform plan

#      - name: Prod Terraform Init
#        working-directory: terraform/environments/prod
#        run: terraform init

#      - name: Prod Terraform Plan
#        working-directory: terraform/environments/prod
#        run: terraform plan