name: 01 Setup Terraform State Backend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy state to'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

jobs:
  deployStateBucket:
    name: Deploy State Bucket
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Envs
        run: |
          mkdir ~/.aws
          echo -e "${{ secrets.SHARED_CREDENTIALS }}" >> ~/.aws/credentials
          echo -e "${{ secrets.SHARED_CONFIG }}" >> ~/.aws/config

      - name: Terraform Init (Local)
        working-directory: terraform/terraform_backends/${{ github.event.inputs.environment }}
        run: terraform init


      - name: Terraform Apply (Create State Bucket and DynamoDB)
        working-directory: terraform/terraform_backends/${{ github.event.inputs.environment }}
        run: terraform apply -auto-approve

      - name: Update Backend Configuration
        if: ${{ vars.DEPLOY_NEW_STATE = "true" }}
        working-directory: terraform/terraform_backends/${{ github.event.inputs.environment }}
        run: |
          # You would dynamically update your Terraform files here if needed
          echo 'Updating backend configuration...'
          cat <<EOF > backend.tf
          terraform {
              backend "s3" {
              bucket = "${{ vars.STATE_BUCKET_PREFIX }}-${{ github.event.inputs.environment }}-backend-tfstate"
              profile = "${{ github.event.inputs.environment }}"
              key = "state-file/terraform.tfstate"
              region = "us-east-2"
              dynamodb_table = "${{ vars.STATE_BUCKET_PREFIX }}-${{ github.event.inputs.environment }}-terraform-locks"
              encrypt = true
              shared_credentials_files = ["~/.aws/credentials"]
            }
          }
          EOF

      - name: Re-Initialize Terraform with S3 Backend and copy state to S3
        if: ${{ vars.DEPLOY_NEW_STATE = "true" }}
        working-directory: terraform/terraform_backends/${{ github.event.inputs.environment }}
        run: terraform init -reconfigure -input=false -force-copy

      - name: Terraform Plan (Check Configuration)
        if: ${{ vars.DEPLOY_NEW_STATE = "true" }}
        working-directory: terraform/terraform_backends/${{ github.event.inputs.environment }}
        run: terraform plan

      - name: Terraform Apply (Final Configuration)
        if: ${{ vars.DEPLOY_NEW_STATE = "true" }}
        working-directory: terraform/terraform_backends/${{ github.event.inputs.environment }}
        run: terraform apply -auto-approve

      - name: Cleanup Local State
        if: ${{ vars.DEPLOY_NEW_STATE = "true" }}
        working-directory: terraform/terraform_backends/${{ github.event.inputs.environment }}
        run: rm -f terraform.tfstate